Run library tests (#497)
#496 made me realize that "library tests" (`zig build test`) don't run
under CI. Many of them were broken by recent PRs. Let's restore them.

For some reason, however
```bash
$ poetry run python -m ziglang build test
test
└─ run test stderr
Exception ignored on threading shutdown:
OverflowError: can't convert negative int to unsigned
$ echo $?
0
```

Not sure whether to worry about it.